import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/AuthProvider/AuthProvider";
import Link from "next/link";
import whatsapp from "@/public/icons/whatsapp.png";
import Image from "next/image";
import { Provider } from "react-redux";
import { store } from "@/Redux/store";
import ReduxProvider from "@/Redux/ReduxProvider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Style Print",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ReduxProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ReduxProvider>

        
      </body>
    </html>
  );
}
