"use client";

import PageLoading from "@/components/adminComponents/PageLoading/PageLoading";
import RelatedCart from "@/components/singleProduct/RelatedCart";
import axios from "axios";
import { Metadata } from "next";
import React, { useEffect, useState } from "react";

type pType = {
  price: string;
  images: string[];
  description: string;
  category: string;
  name: string;
  subCategory: string;
  _id: string;
};
// export const metadata: Metadata = {
//   title: "Style Print | Shops ",
//   description: "Generated by create next app",
// };

const Products = () => {
  const [productData, setProductData] = useState<any>([]);
  const [loading, setLoading] = useState(false)

  useEffect(()=>{
    setLoading(true)
    axios(`/api/products`)
    .then(res => {
      if(res.data){
        setLoading(false)
      }
      setProductData(res.data);
    })
  },[])
  

  return (
    <div className="container mx-auto">
    {
      loading && <div className="flex items-center"><PageLoading></PageLoading></div>
    }
      <div className="grid grid-cols-1  lg:grid-cols-3 md:grid-cols-2 lg:gap-x-6  gap-6 mt-20">
        {productData?.map((item: pType) => (
          <RelatedCart product={item} key={item._id}></RelatedCart>
        ))}
      </div>
    </div>
  );
};

export default Products;
